#General settings
[general]
	#Decides are given the Tome of Knowledge when starting a world
	startWithBook = false
	#Decides the range in which players around you can hear the spells cast (-1 for server spam) [Default: 16]
	#Range: > -1
	proximity = 16
	#Decides whether you use the individual level cost (Cost to level up can be different per level) or use a scaling level cost
	individualLevels = true
	#Decides whether you use the individual item cost (Cost to level up can be different per level) or use a scaling item cost
	individualItems = true
	#Decides whether you need specific items to level up (Default: true)
	requireItems = true
	#Decides whether you need specific items to level up (Default: minecraft:lapis_lazuli)
	requiredItem = "minecraft:lapis_lazuli"
	#Determines how much xp you need to pay per individual level when enabled (XP Levels) [Syntax: level,xp_cost]
	#If you have changed the maxLevel and enabled individualLevels you'll need supply the new individual level costs
	individualLevelCosts = ["1,5", "2,5", "3,5", "4,5", "5,5", "6,5", "7,5", "8,5", "9,5", "10,5", "11,5", "12,5", "13,5", "14,5", "15,5", "16,5", "17,5", "18,5", "19,5", "20,5"]
	#Determines how which item each level costs when 'requireItems' is enabled (XP Levels) [Syntax: level,modid:item_name,amount]
	#If you have changed the maxLevel and enabled requireItems you'll need supply the new individual item costs
	individualItemCosts = ["1,minecraft:lapis_lazuli,10", "2,minecraft:lapis_lazuli,10", "3,minecraft:lapis_lazuli,10", "4,minecraft:lapis_lazuli,10", "5,minecraft:lapis_lazuli,10", "6,minecraft:lapis_lazuli,10", "7,minecraft:lapis_lazuli,10", "8,minecraft:lapis_lazuli,10", "9,minecraft:lapis_lazuli,10", "10,minecraft:lapis_lazuli,10", "11,minecraft:lapis_lazuli,10", "12,minecraft:lapis_lazuli,10", "13,minecraft:lapis_lazuli,10", "14,minecraft:lapis_lazuli,10", "15,minecraft:lapis_lazuli,10", "16,minecraft:lapis_lazuli,10", "17,minecraft:lapis_lazuli,10", "18,minecraft:lapis_lazuli,10", "19,minecraft:lapis_lazuli,10", "20,minecraft:lapis_lazuli,10"]
	#Decides the highest level a player can become (Default: 20)
	#Range: > 1
	maxLevel = 20
	#Decides how much xp you need to pay per level (cost is multiplied * level)
	#Range: > 1
	xpMultiplier = 100
	#Decides whether the tooltip of the Tome of Knowledge tells you what's inside (Default: true)
	hideKnowledgeTomeInfo = true
